// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class DeclarativeTableComponentComponent extends RichDeclarativeComponent {

  public DeclarativeTableComponentComponent() {
  }

  public String getVoName() {
    return (String) getAttributes().get("voName");
  }

  public String getDcName() {
    return (String) getAttributes().get("dcName");
  }

  public String getHeaderText() {
    return (String) getAttributes().get("HeaderText");
  }

  public String getSearchRegion() {
    return (String) getAttributes().get("SearchRegion");
  }



}
