// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class DeclarativeTableComponentTag extends RichDeclarativeComponentTag {

  public DeclarativeTableComponentTag() {
  }

  public String getComponentType() {
    return "component.DeclarativeTableComponentComponentType";
  }

  protected String getViewId() {
    return "/DeclarativeTableComponent.jsf";
  }

  protected RichDeclarativeComponent createComponent() {
    return new DeclarativeTableComponentComponent();
  }

  public void setVoName(ValueExpression voName) {
    this._voName = voName;
  }

  public void setDcName(ValueExpression dcName) {
    this._dcName = dcName;
  }

  public void setHeaderText(ValueExpression HeaderText) {
    this._HeaderText = HeaderText;
  }

  public void setSearchRegion(ValueExpression SearchRegion) {
    this._SearchRegion = SearchRegion;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_voName != null)
      bean.setValueExpression(_VONAME_KEY, _voName);
    if (_dcName != null)
      bean.setValueExpression(_DCNAME_KEY, _dcName);
    if (_HeaderText != null)
      bean.setValueExpression(_HEADERTEXT_KEY, _HeaderText);
    if (_SearchRegion != null)
      bean.setValueExpression(_SEARCHREGION_KEY, _SearchRegion);
  }

  public void release() {
    super.release();
    _voName = null;
    _dcName = null;
    _HeaderText = null;
    _SearchRegion = null;
  }

  private ValueExpression _voName;
  private ValueExpression _dcName;
  private ValueExpression _HeaderText;
  private ValueExpression _SearchRegion;

  private static final PropertyKey _VONAME_KEY = PropertyKey.createPropertyKey("voName");
  private static final PropertyKey _DCNAME_KEY = PropertyKey.createPropertyKey("dcName");
  private static final PropertyKey _HEADERTEXT_KEY = PropertyKey.createPropertyKey("HeaderText");
  private static final PropertyKey _SEARCHREGION_KEY = PropertyKey.createPropertyKey("SearchRegion");

}
