// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import javax.faces.view.facelets.FaceletContext;
import javax.faces.view.facelets.ComponentConfig;
import oracle.adfinternal.view.faces.facelets.rich.IncludeHandler;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;

public class DeclarativeTableComponentHandler extends IncludeHandler {

  private static final String _VIEW_ID = "/DeclarativeTableComponent.jsf";

  public DeclarativeTableComponentHandler(ComponentConfig config) {
    super(config);
  }

  protected String getViewId(FaceletContext ctx) {
    return _VIEW_ID;
  }

  protected RichDeclarativeComponent createComponent() {
    return new DeclarativeTableComponentComponent();
  }

}
